# Generated by Django 5.1.2 on 2024-10-12 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_myimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('one-bedroom', 'One Bedroom'), ('two-bedroom', 'Two Bedroom'), ('studio', 'Studio'), ('special', 'Special')], max_length=50)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='reservations.myimage')),
            ],
        ),
    ]
