# Generated by Django 5.1.2 on 2024-10-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_espacededetente'),
    ]

    operations = [
        migrations.AddField(
            model_name='myimage',
            name='local',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
